import type { GlobalSourceSeed } from './globalSourceRegistry';

// Generated by scripts/import-global-events.ts from the Global Events workbook.
// Rows without public http(s) URLs are intentionally excluded until they have source pages.
export const IMPORTED_GLOBAL_EVENT_SEEDS: GlobalSourceSeed[] = [
  {
    "id": "imported-event-modex-2026-atlanta-ga-2026",
    "name": "Modex 2026",
    "type": "event",
    "region": "americas",
    "url": "https://www.modexshow.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: April 13–16, 2026 · Atlanta, GA · Edge/CV focus · Tier 4: No support · Activation: Tier 4: No Support.",
    "eventDate": "April 13–16, 2026",
    "location": "Atlanta, GA",
    "focusArea": "Edge/CV",
    "eventTier": "Tier 4: No support",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 3
  },
  {
    "id": "imported-event-tomorrow-city-west-palm-beach-2026",
    "name": "Tomorrow City",
    "type": "event",
    "region": "americas",
    "url": "https://tomorrowcity.us/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: April 14-15, 2026 · WEST PALM BEACH · Edge/CV focus · Tier 4: No support · Activation: Tier 4: No Support.",
    "eventDate": "April 14-15, 2026",
    "location": "WEST PALM BEACH",
    "focusArea": "Edge/CV",
    "eventTier": "Tier 4: No support",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 4
  },
  {
    "id": "imported-event-ai-ascent-san-francisco-ca-2026",
    "name": "AI Ascent",
    "type": "event",
    "region": "americas",
    "url": "https://sequoiacap.com/",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: April 20, 2026 · San Francisco, CA · Robotics focus · Tier 4: No support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "April 20, 2026",
    "location": "San Francisco, CA",
    "focusArea": "Robotics",
    "eventTier": "Tier 4: No support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 6
  },
  {
    "id": "imported-event-google-cloud-next-las-vegas-nv-2026",
    "name": "Google Cloud NEXT",
    "type": "event",
    "region": "americas",
    "url": "https://www.googlecloudevents.com/next-vegas/?i=lQ67NvMaLyHB23Nq1R2mpDU5dNAiC0m7",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: April 22-24, 2026 · Las Vegas, NV · Physical AI focus · Tier 3: Minor digital support, amp · Activation: Tier 3: No major partners, self-service.",
    "eventDate": "April 22-24, 2026",
    "location": "Las Vegas, NV",
    "focusArea": "Physical AI",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 3: No major partners, self-service",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 7
  },
  {
    "id": "imported-event-iclr-2026-rio-de-janeiro-brazil-2026",
    "name": "ICLR 2026",
    "type": "event",
    "region": "americas",
    "url": "https://iclr.cc/",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: April 23–27, 2026 · Rio de Janeiro, Brazil · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 3: No major partners, self-service.",
    "eventDate": "April 23–27, 2026",
    "location": "Rio de Janeiro, Brazil",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 3: No major partners, self-service",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 8
  },
  {
    "id": "imported-event-actuate-san-francisco-ca-2026",
    "name": "Actuate",
    "type": "event",
    "region": "americas",
    "url": "https://actuate.foxglove.dev/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: August 18-19, 2026 · San Francisco, CA · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "August 18-19, 2026",
    "location": "San Francisco, CA",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 31
  },
  {
    "id": "imported-event-siggraph-los-angeles-ca-2026",
    "name": "SIGGRAPH",
    "type": "event",
    "region": "americas",
    "url": "https://s2026.siggraph.org/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "embodied AI",
      "Industrial Digital Twins",
      "Physical AI",
      "Robotics",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: July 19-23, 2026 · Los Angeles, CA · Physical AI focus · Tier 2: Major digital support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "July 19-23, 2026",
    "location": "Los Angeles, CA",
    "focusArea": "Physical AI",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 30
  },
  {
    "id": "imported-event-microsoft-build-san-francisco-ca-2026",
    "name": "Microsoft Build",
    "type": "event",
    "region": "americas",
    "url": "https://build.microsoft.com/",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: June 2-3, 2026 · San Francisco, CA · Physical AI focus.",
    "eventDate": "June 2-3, 2026",
    "location": "San Francisco, CA",
    "focusArea": "Physical AI",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 21
  },
  {
    "id": "imported-event-automate-chicago-il-2026",
    "name": "Automate",
    "type": "event",
    "region": "americas",
    "url": "https://www.automateshow.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: June 22–25, 2026 · Chicago, IL · Robotics focus · Tier 2: Major digital support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "June 22–25, 2026",
    "location": "Chicago, IL",
    "focusArea": "Robotics",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 26
  },
  {
    "id": "imported-event-cvpr-denver-co-2026",
    "name": "CVPR",
    "type": "event",
    "region": "americas",
    "url": "https://cvpr.thecvf.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Metropolis",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "embodied AI",
      "Intelligent Vision AI",
      "Physical AI",
      "Robotics",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: June 3-7, 2026 · Denver, CO · Physical AI focus · Tier 2: Major digital support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "June 3-7, 2026",
    "location": "Denver, CO",
    "focusArea": "Physical AI",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 23
  },
  {
    "id": "imported-event-apple-wwdc-cupertino-ca-2026",
    "name": "Apple WWDC",
    "type": "event",
    "region": "americas",
    "url": "https://developer.apple.com/wwdc",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: June 8-12, 2026 · Cupertino, CA · Physical AI focus · Tier 4: No support.",
    "eventDate": "June 8-12, 2026",
    "location": "Cupertino, CA",
    "focusArea": "Physical AI",
    "eventTier": "Tier 4: No support",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 24
  },
  {
    "id": "imported-event-sap-sapphire-orlando-fl-2026",
    "name": "SAP Sapphire",
    "type": "event",
    "region": "americas",
    "url": "https://events.sap.com/sapphire",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: May 11-13, 2026 · Orlando, FL · Physical AI focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "May 11-13, 2026",
    "location": "Orlando, FL",
    "focusArea": "Physical AI",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 11
  },
  {
    "id": "imported-event-xponential-auvsi-detroit-mi-2026",
    "name": "XPONENTIAL (AUVSI)",
    "type": "event",
    "region": "americas",
    "url": "https://www.xponential.org/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Metropolis",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "embodied AI",
      "Intelligent Vision AI",
      "Physical AI",
      "Robotics",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: May 11-14, 2026 · Detroit, MI · Edge/CV focus · Tier 4: No support · Activation: Tier 4: No Support.",
    "eventDate": "May 11-14, 2026",
    "location": "Detroit, MI",
    "focusArea": "Edge/CV",
    "eventTier": "Tier 4: No support",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 12
  },
  {
    "id": "imported-event-scifm-2026-chicago-il-2026",
    "name": "SciFM 2026",
    "type": "event",
    "region": "americas",
    "url": "https://www.scifmconferences.org/program",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: May 27-29, 2026 · Chicago, IL · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 4: No Support.",
    "eventDate": "May 27-29, 2026",
    "location": "Chicago, IL",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 16
  },
  {
    "id": "imported-event-boston-robotics-summit-boston-ma-2026",
    "name": "Boston Robotics Summit",
    "type": "event",
    "region": "americas",
    "url": "https://www.roboticssummit.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: May 27–28, 2026 · Boston, MA · Physical AI focus · Tier 3: Minor digital support, amp · Activation: Tier 4: No Support.",
    "eventDate": "May 27–28, 2026",
    "location": "Boston, MA",
    "focusArea": "Physical AI",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 18
  },
  {
    "id": "imported-event-aws-re-invent-2026-las-vegas-nv-2026",
    "name": "AWS re:Invent 2026",
    "type": "event",
    "region": "americas",
    "url": "https://reinvent.awsevents.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: November 30 - December 4, 2026 · Las Vegas, NV · Physical AI focus · Tier 2: Major digital support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "November 30 - December 4, 2026",
    "location": "Las Vegas, NV",
    "focusArea": "Physical AI",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 44
  },
  {
    "id": "imported-event-corl-austin-texas-2026",
    "name": "CoRL",
    "type": "event",
    "region": "americas",
    "url": "https://www.corl.org/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: November 9-12, 2026 · Austin, Texas · Robotics focus · Tier 2: Major digital support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "November 9-12, 2026",
    "location": "Austin, Texas",
    "focusArea": "Robotics",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 42
  },
  {
    "id": "imported-event-robobusiness-santa-clara-ca-2026",
    "name": "RoboBusiness",
    "type": "event",
    "region": "americas",
    "url": "https://www.robobusiness.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: October 19-21, 2026 · Santa Clara, CA · Robotics focus.",
    "eventDate": "October 19-21, 2026",
    "location": "Santa Clara, CA",
    "focusArea": "Robotics",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 40
  },
  {
    "id": "imported-event-autodesk-university-las-vegas-nv-2026",
    "name": "Autodesk University",
    "type": "event",
    "region": "americas",
    "url": "https://www.autodesk.com/university",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "embodied AI",
      "Industrial Digital Twins",
      "Physical AI",
      "Robotics",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: September 15-17, 2026 · Las Vegas, NV · Physical AI focus.",
    "eventDate": "September 15-17, 2026",
    "location": "Las Vegas, NV",
    "focusArea": "Physical AI",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 34
  },
  {
    "id": "imported-event-embedded-world-us-anaheim-ca-2026",
    "name": "Embedded World (US)",
    "type": "event",
    "region": "americas",
    "url": "https://embedded-world-na.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: September 22-24, 2026 · Anaheim, CA · Edge/CV focus · Tier 2: Major digital support · Activation: Tier 1: Max floorshow coverage possible.",
    "eventDate": "September 22-24, 2026",
    "location": "Anaheim, CA",
    "focusArea": "Edge/CV",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 1: Max floorshow coverage possible",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 35
  },
  {
    "id": "imported-event-embedded-world-north-america-anaheim-convention-center-an-2026",
    "name": "Embedded World North America",
    "type": "event",
    "region": "americas",
    "url": "https://embedded-world-na.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: September 22–24, 2026 · Anaheim Convention Center (Anaheim, CA) · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "September 22–24, 2026",
    "location": "Anaheim Convention Center (Anaheim, CA)",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 37
  },
  {
    "id": "imported-event-iros-pittsburgh-pa-2026",
    "name": "IROS",
    "type": "event",
    "region": "americas",
    "url": "https://2026.ieee-iros.org/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: September 27 - October 1, 2026 · Pittsburgh, PA · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "September 27 - October 1, 2026",
    "location": "Pittsburgh, PA",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 38
  },
  {
    "id": "imported-event-neurips-sydney-australia-2026",
    "name": "NeurIPS",
    "type": "event",
    "region": "apac",
    "url": "https://neurips.cc/",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: December 6-12, 2026 · Sydney, Australia · Physical AI focus · Tier 2: Major digital support · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "December 6-12, 2026",
    "location": "Sydney, Australia",
    "focusArea": "Physical AI",
    "eventTier": "Tier 2: Major digital support",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 45
  },
  {
    "id": "imported-event-rss-sydney-australia-2026",
    "name": "RSS",
    "type": "event",
    "region": "apac",
    "url": "https://roboticsconference.org/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: July 13-17, 2026 · Sydney, Australia · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "July 13-17, 2026",
    "location": "Sydney, Australia",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 29
  },
  {
    "id": "imported-event-computex-gtc-taipei-taipei-taiwan-2026",
    "name": "COMPUTEX/GTC Taipei",
    "type": "event",
    "region": "apac",
    "url": "https://www.computextaipei.com.tw/en/index.html",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: June 2–5, 2026 · Taipei, Taiwan · Physical AI focus · Tier 1: All-in, full support · Activation: Tier 1: Max floorshow coverage possible.",
    "eventDate": "June 2–5, 2026",
    "location": "Taipei, Taiwan",
    "focusArea": "Physical AI",
    "eventTier": "Tier 1: All-in, full support",
    "activationTier": "Tier 1: Max floorshow coverage possible",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 22
  },
  {
    "id": "imported-event-beyond-expo-macao-china-2026",
    "name": "BEYOND EXPO",
    "type": "event",
    "region": "apac",
    "url": "https://www.beyondexpo.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: May 27-30, 2026 · Macao, China · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 4: No Support.",
    "eventDate": "May 27-30, 2026",
    "location": "Macao, China",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 17
  },
  {
    "id": "imported-event-hannover-messe-hannover-germany-2026",
    "name": "Hannover Messe",
    "type": "event",
    "region": "emea",
    "url": "https://www.hannovermesse.de/en/",
    "products": [
      "Isaac Sim",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "Industrial Digital Twins",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: Apr 20 - 24, 2026 · Hannover, Germany · Industrial AI focus · Tier 1: All-in, full support · Activation: Tier 1: Max floorshow coverage possible.",
    "eventDate": "Apr 20 - 24, 2026",
    "location": "Hannover, Germany",
    "focusArea": "Industrial AI",
    "eventTier": "Tier 1: All-in, full support",
    "activationTier": "Tier 1: Max floorshow coverage possible",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 19
  },
  {
    "id": "imported-event-the-security-event-birmingham-uk-2026",
    "name": "The Security Event",
    "type": "event",
    "region": "emea",
    "url": "https://www.thesecurityevent.co.uk/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Apr 28-30, 2026 · Birmingham, UK · Smart Spaces focus.",
    "eventDate": "Apr 28-30, 2026",
    "location": "Birmingham, UK",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 20
  },
  {
    "id": "imported-event-ai-conference-armenia-2026",
    "name": "AI Conference",
    "type": "event",
    "region": "emea",
    "url": "https://www.ysu.am/en/conference/AIConf26",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: April 18, 2026 · Armenia · Physical AI focus · Tier 3: Minor digital support, amp · Activation: Tier 4: No Support.",
    "eventDate": "April 18, 2026",
    "location": "Armenia",
    "focusArea": "Physical AI",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 5
  },
  {
    "id": "imported-event-hpe-discover-barcelona-spain-2026",
    "name": "HPE Discover",
    "type": "event",
    "region": "emea",
    "url": "https://www.hpe.com/us/en/discover/barcelona.html",
    "products": [
      "Cosmos",
      "DGX Spark",
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "edge AI",
      "Intelligent Vision AI",
      "Physical AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Dec 2 - 3, 2026 · Barcelona, Spain · Smart Spaces focus.",
    "eventDate": "Dec 2 - 3, 2026",
    "location": "Barcelona, Spain",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 42
  },
  {
    "id": "imported-event-gitex-global-dubai-uae-2026",
    "name": "Gitex Global",
    "type": "event",
    "region": "emea",
    "url": "https://www.gitex.com/gitex-global-2026",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Dec 7 - 11, 2026 · Dubai, UAE · Smart Spaces focus.",
    "eventDate": "Dec 7 - 11, 2026",
    "location": "Dubai, UAE",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 43
  },
  {
    "id": "imported-event-industrial-metaverse-conference-munich-germany-2026",
    "name": "Industrial Metaverse Conference",
    "type": "event",
    "region": "emea",
    "url": "https://www.industrial-metaverse-conference.com/",
    "products": [
      "Isaac Sim",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "Industrial Digital Twins",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: Feb 10 - 11, 2026 · Munich, Germany · Manufacturing focus · Tier 3: Minor digital support, amp · Activation: Tier 4: No Support.",
    "eventDate": "Feb 10 - 11, 2026",
    "location": "Munich, Germany",
    "focusArea": "Manufacturing",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 5
  },
  {
    "id": "imported-event-international-humanoid-forum-biel-switzerland-2026",
    "name": "International Humanoid Forum",
    "type": "event",
    "region": "emea",
    "url": "https://humanoid-forum.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: Feb 19-20, 2026 · Biel, Switzerland · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "Feb 19-20, 2026",
    "location": "Biel, Switzerland",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 6
  },
  {
    "id": "imported-event-proptech-connect-dubai-uae-2026",
    "name": "PropTech Connect",
    "type": "event",
    "region": "emea",
    "url": "https://proptechconnect.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Feb 4 - 6, 2026 · Dubai, UAE · Smart Spaces focus · Tier 4: No support · Activation: Tier 4: No Support.",
    "eventDate": "Feb 4 - 6, 2026",
    "location": "Dubai, UAE",
    "focusArea": "Smart Spaces",
    "eventTier": "Tier 4: No support",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 4
  },
  {
    "id": "imported-event-machines-can-think-abhu-dhabi-uae-2026",
    "name": "Machines can Think",
    "type": "event",
    "region": "emea",
    "url": "https://machinescanthink.ai/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Jan 26 - 27, 2026 · Abhu Dhabi, UAE · Smart Spaces focus · Tier 3: Minor digital support, amp · Activation: Tier 3: No major partners, self-service.",
    "eventDate": "Jan 26 - 27, 2026",
    "location": "Abhu Dhabi, UAE",
    "focusArea": "Smart Spaces",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 3: No major partners, self-service",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 3
  },
  {
    "id": "imported-event-raise-summit-machina-paris-france-2026",
    "name": "Raise Summit / MACHINA",
    "type": "event",
    "region": "emea",
    "url": "https://www.raisesummit.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: July 7-9, 2026 · Paris, France · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 4: No Support.",
    "eventDate": "July 7-9, 2026",
    "location": "Paris, France",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 4: No Support",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 28
  },
  {
    "id": "imported-event-emea-humanoid-robot-summit-munich-germany-2026",
    "name": "EMEA Humanoid Robot Summit",
    "type": "event",
    "region": "emea",
    "url": "http://robot.clcc-sh.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: Jun 16 - 17, 2026 · Munich, Germany · Robotics focus · Tier 4: No support · Activation: TBD - pending ecosystem participation.",
    "eventDate": "Jun 16 - 17, 2026",
    "location": "Munich, Germany",
    "focusArea": "Robotics",
    "eventTier": "Tier 4: No support",
    "activationTier": "TBD - pending ecosystem participation",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 33
  },
  {
    "id": "imported-event-icra-vienna-austria-2026",
    "name": "ICRA",
    "type": "event",
    "region": "emea",
    "url": "https://2026.ieee-icra.org/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: June 1–5, 2026 · Vienna, Austria · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "June 1–5, 2026",
    "location": "Vienna, Austria",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 20
  },
  {
    "id": "imported-event-embedded-world-emea-nuremberg-germany-2026",
    "name": "Embedded World EMEA",
    "type": "event",
    "region": "emea",
    "url": "https://www.embedded-world.de/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: Mar 10 - 12, 2026 · Nuremberg, Germany · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 3: No major partners, self-service.",
    "eventDate": "Mar 10 - 12, 2026",
    "location": "Nuremberg, Germany",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 3: No major partners, self-service",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 9
  },
  {
    "id": "imported-event-intertraffic-amsterdam-netherlands-2026",
    "name": "Intertraffic",
    "type": "event",
    "region": "emea",
    "url": "https://www.intertraffic.com/amsterdam",
    "products": [
      "Alpamayo",
      "DriveOS",
      "Halos",
      "Metropolis",
      "NVIDIA Jetson",
      "NVIDIA Omniverse"
    ],
    "topics": [
      "autonomous driving",
      "AV",
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces",
      "software-defined vehicles"
    ],
    "description": "Imported from the Global Events workbook: Mar 10 - 13, 2026 · Amsterdam, Netherlands · Smart Spaces focus.",
    "eventDate": "Mar 10 - 13, 2026",
    "location": "Amsterdam, Netherlands",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 10
  },
  {
    "id": "imported-event-passenger-terminal-expo-london-uk-2026",
    "name": "Passenger Terminal Expo",
    "type": "event",
    "region": "emea",
    "url": "https://www.pte-world.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Mar 17 - 19, 2026 · London, UK · Smart Spaces focus.",
    "eventDate": "Mar 17 - 19, 2026",
    "location": "London, UK",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 12
  },
  {
    "id": "imported-event-mwc-and-talent-arena-barcelona-spain-2026",
    "name": "MWC (& talent arena)-",
    "type": "event",
    "region": "emea",
    "url": "https://www.mwcbarcelona.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Mar 2–5, 2026 · Barcelona, Spain · N/A focus · Tier 3: Minor digital support, amp · Activation: Tier 3: No major partners, self-service.",
    "eventDate": "Mar 2–5, 2026",
    "location": "Barcelona, Spain",
    "focusArea": "N/A",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 3: No major partners, self-service",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 7
  },
  {
    "id": "imported-event-european-robotics-forum-erf-norway-2026",
    "name": "European Robotics Forum (ERF)",
    "type": "event",
    "region": "emea",
    "url": "https://erf2026.eu/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: Mar 23 - 27, 2026 · Norway · Robotics focus.",
    "eventDate": "Mar 23 - 27, 2026",
    "location": "Norway",
    "focusArea": "Robotics",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 13
  },
  {
    "id": "imported-event-xponential-dusseldorf-germany-2026",
    "name": "XPonential",
    "type": "event",
    "region": "emea",
    "url": "https://www.xponential-europe.com/en/Visitors/What_to_expect/Reasons_to_attend",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: Mar 24 - 26, 2026 · Dusseldorf, Germany.",
    "eventDate": "Mar 24 - 26, 2026",
    "location": "Dusseldorf, Germany",
    "focusArea": "",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 16
  },
  {
    "id": "imported-event-logimat-stuttgart-germany-2026",
    "name": "Logimat",
    "type": "event",
    "region": "emea",
    "url": "https://www.logimat-messe.de/",
    "products": [
      "Isaac Sim",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "Industrial Digital Twins",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: Mar 24-26, 2026 · Stuttgart, Germany · Manufacturing focus.",
    "eventDate": "Mar 24-26, 2026",
    "location": "Stuttgart, Germany",
    "focusArea": "Manufacturing",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 14
  },
  {
    "id": "imported-event-gartner-supply-chain-symposium-barcelona-spain-2026",
    "name": "Gartner Supply Chain Symposium",
    "type": "event",
    "region": "emea",
    "url": "https://www.gartner.com/en/conferences/emea/supply-chain-spain",
    "products": [
      "Isaac Sim",
      "Metropolis",
      "NVIDIA Jetson",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "edge AI",
      "Industrial Digital Twins",
      "Intelligent Vision AI",
      "simulation",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: May 18-20, 2026 · Barcelona, Spain · Smart Spaces focus.",
    "eventDate": "May 18-20, 2026",
    "location": "Barcelona, Spain",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 25
  },
  {
    "id": "imported-event-aveva-world-milan-it-2026",
    "name": "AVEVA World",
    "type": "event",
    "region": "emea",
    "url": "https://events.aveva.com/aw-2026/",
    "products": [
      "Isaac Sim",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "Industrial Digital Twins",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: May 19-21, 2026 · Milan, IT.",
    "eventDate": "May 19-21, 2026",
    "location": "Milan, IT",
    "focusArea": "",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 27
  },
  {
    "id": "imported-event-uk-real-estate-investment-and-infrastructure-forum-leeds-uk-2026",
    "name": "UK Real Estate Investment & Infrastructure Forum",
    "type": "event",
    "region": "emea",
    "url": "https://2026.ukreiif.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: May 19-21, 2026 · Leeds, UK · Smart Spaces focus.",
    "eventDate": "May 19-21, 2026",
    "location": "Leeds, UK",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 26
  },
  {
    "id": "imported-event-week-of-robotics-odense-denmark-2026",
    "name": "Week of Robotics",
    "type": "event",
    "region": "emea",
    "url": "https://www.odenserobotics.dk/week-of-robotics/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: May 5-8, 2026 · Odense, Denmark · Robotics focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "May 5-8, 2026",
    "location": "Odense, Denmark",
    "focusArea": "Robotics",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 9
  },
  {
    "id": "imported-event-swiss-robotics-day-zurich-switzerland-2026",
    "name": "Swiss Robotics Day",
    "type": "event",
    "region": "emea",
    "url": "https://swissroboticsday.ch/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: Nov 13, 2026 · Zurich, Switzerland · Robotics focus.",
    "eventDate": "Nov 13, 2026",
    "location": "Zurich, Switzerland",
    "focusArea": "Robotics",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 40
  },
  {
    "id": "imported-event-sps-nuremberg-nuremberg-germany-2026",
    "name": "SPS Nuremberg",
    "type": "event",
    "region": "emea",
    "url": "https://sps.mesago.com/nuernberg/en.html",
    "products": [
      "Isaac Sim",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "CAE",
      "Industrial Digital Twins",
      "simulation"
    ],
    "description": "Imported from the Global Events workbook: Nov 24 - 26, 2026 · Nuremberg, Germany.",
    "eventDate": "Nov 24 - 26, 2026",
    "location": "Nuremberg, Germany",
    "focusArea": "",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 41
  },
  {
    "id": "imported-event-smart-city-expo-barcelona-spain-2026",
    "name": "Smart City Expo",
    "type": "event",
    "region": "emea",
    "url": "https://www.smartcityexpo.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: November 3–5, 2026 · Barcelona, Spain · Edge/CV focus · Tier 3: Minor digital support, amp · Activation: Tier 1: Max floorshow coverage possible.",
    "eventDate": "November 3–5, 2026",
    "location": "Barcelona, Spain",
    "focusArea": "Edge/CV",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 1: Max floorshow coverage possible",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 41
  },
  {
    "id": "imported-event-web-summit-lisbon-2026-lisbon-portugal-2026",
    "name": "Web Summit Lisbon 2026",
    "type": "event",
    "region": "emea",
    "url": "https://websummit.com/",
    "products": [
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: November 9–12, 2026 · Lisbon, Portugal · Physical AI focus.",
    "eventDate": "November 9–12, 2026",
    "location": "Lisbon, Portugal",
    "focusArea": "Physical AI",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 43
  },
  {
    "id": "imported-event-iaa-transportation-hannover-germany-2026",
    "name": "IAA Transportation",
    "type": "event",
    "region": "emea",
    "url": "https://www.iaa-transportation.com/en",
    "products": [
      "Alpamayo",
      "DriveOS",
      "Halos",
      "Isaac Sim",
      "NVIDIA Omniverse",
      "OpenUSD"
    ],
    "topics": [
      "autonomous driving",
      "AV",
      "CAE",
      "Industrial Digital Twins",
      "simulation",
      "software-defined vehicles"
    ],
    "description": "Imported from the Global Events workbook: Sep 15 - 20, 2026 · Hannover, Germany · Automotive focus.",
    "eventDate": "Sep 15 - 20, 2026",
    "location": "Hannover, Germany",
    "focusArea": "Automotive",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 35
  },
  {
    "id": "imported-event-international-security-expo-london-uk-2026",
    "name": "International Security Expo",
    "type": "event",
    "region": "emea",
    "url": "https://www.internationalsecurityexpo.com/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: Sep 29-30, 2026 · London, UK · Smart Spaces focus.",
    "eventDate": "Sep 29-30, 2026",
    "location": "London, UK",
    "focusArea": "Smart Spaces",
    "eventTier": "",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - EMEA",
    "sourceRow": 37
  },
  {
    "id": "imported-event-humanx-amsterdam-netherlands-2026",
    "name": "HumanX",
    "type": "event",
    "region": "emea",
    "url": "https://www.humanx.co/europe",
    "products": [
      "Cosmos",
      "DGX Spark",
      "GR00T",
      "Isaac Lab",
      "Isaac ROS",
      "Isaac Sim",
      "Newton",
      "NVIDIA Jetson"
    ],
    "topics": [
      "AI infrastructure",
      "embodied AI",
      "Physical AI",
      "Robotics"
    ],
    "description": "Imported from the Global Events workbook: September 22–24, 2026 · Amsterdam, Netherlands · Physical AI focus · Tier 3: Minor digital support, amp · Activation: Tier 2: Activate P0/P1 partners.",
    "eventDate": "September 22–24, 2026",
    "location": "Amsterdam, Netherlands",
    "focusArea": "Physical AI",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "Tier 2: Activate P0/P1 partners",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 36
  },
  {
    "id": "imported-event-eccv-malmo-sweden-2026",
    "name": "ECCV",
    "type": "event",
    "region": "emea",
    "url": "https://eccv.ecva.net/",
    "products": [
      "Metropolis",
      "NVIDIA Jetson"
    ],
    "topics": [
      "edge AI",
      "Intelligent Vision AI",
      "smart spaces"
    ],
    "description": "Imported from the Global Events workbook: September 8-13, 2026 · Malmo, Sweden · Edge/CV focus · Tier 3: Minor digital support, amp.",
    "eventDate": "September 8-13, 2026",
    "location": "Malmo, Sweden",
    "focusArea": "Edge/CV",
    "eventTier": "Tier 3: Minor digital support, amp",
    "activationTier": "",
    "sourceFile": "Global Events.xlsx",
    "sourceSheet": "Events - USA",
    "sourceRow": 32
  }
];
